name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, ctype, iconv, intl, phar
          tools: composer:v2, box

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Build .phar
        run: box compile

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: builds/lx.phar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
